#!/usr/bin/env bash
# gen_nasm_compile_commands.sh
#
# Merges NASM assembly source files into compile_commands.json and generates
# .asm-lsp.toml so that asm-lsp can provide LSP features for .asm files.
#
# Usage: scripts/gen_nasm_compile_commands.sh <source_dir> <build_dir>
#   source_dir  Project root (where src/ lives)
#   build_dir   CMake binary dir that already contains compile_commands.json
#
# Requirements: jq (for JSON manipulation), nasm (for the compiler path)

set -euo pipefail

SOURCE_DIR="$(realpath "${1:-.}")"
BUILD_DIR="$(realpath "${2:-${SOURCE_DIR}/build}")"
COMPILE_COMMANDS="${BUILD_DIR}/compile_commands.json"

if [ ! -f "${COMPILE_COMMANDS}" ]; then
    echo "ERROR: ${COMPILE_COMMANDS} not found. Run cmake first." >&2
    exit 1
fi

NASM="${CMAKE_ASM_NASM_COMPILER:-$(command -v nasm)}"

# ---------------------------------------------------------------------------
# Build the list of NASM entries as a JSON array using jq's --arg / --argjson
# ---------------------------------------------------------------------------

# Helper: emit one JSON object for a NASM source file.
# Arguments: file  directory  command
make_entry() {
    local file="$1"
    local dir="$2"
    local cmd="$3"
    printf '{"file":"%s","directory":"%s","command":"%s"}\n' "$file" "$dir" "$cmd"
}

NASM_ENTRIES="[]"

# Walk every .asm file under src/
while IFS= read -r -d '' asm_file; do
    abs_file="$(realpath "${asm_file}")"
    base="$(basename "${asm_file}" .asm)"
    abs_dir="$(dirname "${abs_file}")"

    # Derive output path and flags based on the file's role:
    #   boot.asm  → flat binary (-f bin), output in build mirror dir
    #   *.asm     → ELF object (-f elf -g), output alongside source in build

    case "${base}" in
        boot)
            # Strip SOURCE_DIR prefix to get the relative path under src/
            rel_dir="${abs_dir#${SOURCE_DIR}/}"
            out_dir="${BUILD_DIR}/${rel_dir}"
            out="${out_dir}/${base}.bin"
            flags="-f bin"
            ;;
        *)
            rel_dir="${abs_dir#${SOURCE_DIR}/}"
            out_dir="${BUILD_DIR}/${rel_dir}"
            out="${out_dir}/${base}.asm.o"
            flags="-f elf -g"
            ;;
    esac

    cmd="${NASM} ${flags} -o ${out} ${abs_file}"
    entry="$(make_entry "${abs_file}" "${out_dir}" "${cmd}")"
    NASM_ENTRIES="$(printf '%s' "${NASM_ENTRIES}" | jq ". += [${entry}]")"

done < <(find "${SOURCE_DIR}/src" -name "*.asm" -print0 | sort -z)

# ---------------------------------------------------------------------------
# Merge: keep all non-.asm entries from CMake, replace/add our NASM entries
# ---------------------------------------------------------------------------

# Remove any previous NASM entries (identified by .asm file extension)
MERGED="$(jq '[.[] | select(.file | endswith(".asm") | not)]' "${COMPILE_COMMANDS}")"

# Append our freshly-built NASM entries
MERGED="$(printf '%s\n%s\n' "${MERGED}" "${NASM_ENTRIES}" | jq -s '.[0] + .[1] | sort_by(.file)')"

# Write back atomically
TMP="$(mktemp "${COMPILE_COMMANDS}.XXXXXXXX")"
printf '%s\n' "${MERGED}" > "${TMP}"
mv "${TMP}" "${COMPILE_COMMANDS}"

echo "compile_commands.json updated: $(printf '%s' "${NASM_ENTRIES}" | jq 'length') NASM entries merged."

# ---------------------------------------------------------------------------
# Generate .asm-lsp.toml in the project root
# ---------------------------------------------------------------------------
ASM_LSP_TOML="${SOURCE_DIR}/.asm-lsp.toml"
cat > "${ASM_LSP_TOML}" <<'TOML'
# Generated by scripts/gen_nasm_compile_commands.sh
# asm-lsp configuration — https://github.com/bergercookie/asm-lsp
#
# asm-lsp discovers compile_commands.json automatically by walking up from
# the opened file's directory, the same way clangd does.

[default_config]
assembler = "NASM"
instruction_set = "x86"
TOML

echo ".asm-lsp.toml written to ${ASM_LSP_TOML}"
